=== jedi-academy/example-schema/general/books2.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" >

<xs:element name="books">
    <xs:complexType>
      <xs:sequence>
	<xs:element name="book" type="booktype" maxOccurs="99"/>
      </xs:sequence>
    </xs:complexType>
</xs:element>

<xs:complexType name="booktype" mixed="true">
  <xs:sequence> 
    <xs:element name="title" type="xs:string"/>
    <xs:element name="translation" type="talktype" maxOccurs="99"/>
  </xs:sequence>
</xs:complexType>

<xs:complexType name="talktype" mixed="true">
  <xs:attribute name="edition"
                   type="xs:positiveInteger"/>
</xs:complexType>

</xs:schema>

=== jedi-academy/example-schema/general/books2.xml
<?xml version = "1.0"?>
<books 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="books2.xsd"	>
   <book> 
      <title>Alice in Wonderland</title>
      <translation edition = "1">Spanish</translation>
      <translation edition = "1">Chinese</translation>
      <translation edition = "1">Japanese</translation>
      <translation edition = "2">French</translation>
      <translation edition = "2">Japanese</translation>
   </book>
   <book> 
      <title>Around the world in 80 days</title>
      <translation edition = "1">Korean</translation>
      <translation edition = "2">French</translation>
      <translation edition = "2">Spanish</translation>
      <translation edition = "3">Italian</translation>
      <translation edition = "3">Japanese</translation>
   </book>
</books>
